export class DataFlow {
  Flow1 = new Flow1();
  Flow2 = new Flow2();
  Flow3 = new Flow3();
  Flow4 = new Flow4();
  Flow5 = new Flow5();
  Flow6 = new Flow6();
  Flow7 = new Flow7();
  Flow8 = new Flow8();
  Flow9 = new Flow9();
  Flow10 = new Flow10();
  Flow11 = new Flow11();
}

export class LevelDatas {
  Flow_No: number = null;
  Level_No: number = null;
  Level_Sno: number = null;
  Level_Index: number = null;
  ItemId: number = null;
  tableName: string = "";
  primaryKey: string = "";
  Name: string = "";
  ItemName: string = "";
  fieldNameKey: string = "";
  NextButtonEnableStatus: boolean = false;
  LevelContinue: boolean = false;
  FormData: any = [];
  tempFormData: any = [];
  skipColumns: [];
  uniqueId: string = "";
  childSno: any = [];
}

// Flow-1
export class Flow1 {
  Data = [
    {
      Flow_No: 1,
      Level_No: 1,
      Level_Name: "Power Transformer",
      Level_Data: [
        {
          Flow_No: 1,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "PT_DATA",
          Level_TabName: "pt_name_plate_details",
          Level_Primary_Key: "PT_Id",
          Item_Name: "Power Transformer",
          Item_Count: 0,
          ItemKey: "PT_Id",
          defaultNameField: "PT_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [1],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 2,
      Level_Name: "Distribution Transformer",
      Level_Data: [
        {
          Flow_No: 1,
          Level_No: 2,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "DT_DATA",
          Level_TabName: "dt_name_plate_details",
          Level_Primary_Key: "DT_Id",
          Item_Name: "Distribution Transformer",
          Item_Count: 0,
          ItemKey: "DT_Id",
          defaultNameField: "DT_Name",
          LevelContinue: true,
          Level_Index: 1,
          skipColumns: [],
          child_Sno: [1],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 3,
      Level_Name: "Power House",
      Level_Data: [
        {
          Flow_No: 1,
          Level_No: 3,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "PH_DATA",
          Level_TabName: "power_house_details",
          Level_Primary_Key: "PH_Id",
          Item_Name: "Power House",
          Item_Count: 0,
          ItemKey: "PH_Id",
          defaultNameField: "PH_Name",
          LevelContinue: true,
          Level_Index: 2,
          skipColumns: [],
          child_Sno: [1],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 4,
      Level_Name: "MV Panel",
      Level_Data: [
        {
          Flow_No: 1,
          Level_No: 4,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "MV_DATA",
          Level_TabName: "mv_panel_details",
          Level_Primary_Key: "MV_Panel_Id",
          Item_Name: "MV Panel",
          Item_Count: 0,
          ItemKey: "MV_Panel_Id",
          defaultNameField: "MV_Panel_Name",
          LevelContinue: true,
          Level_Index: 3,
          skipColumns: [],
          child_Sno: [1, 2],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 5,
      Level_Name: "Capacitor / Department Feeder",
      Level_Data: [
        {
          Flow_No: 1,
          Level_No: 5,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "CAP_DATA",
          Level_TabName: null,
          Level_Primary_Key: "Cap_id",
          Item_Name: "Capacitor",
          Item_Count: 0,
          ItemKey: "Cap_id",
          defaultNameField: "Cap_Name",
          LevelContinue: false,
          Level_Index: 4,
          skipColumns: ["Feeder_id"],
          child_Sno: [],
        },
        {
          Flow_No: 1,
          Level_No: 5,
          Level_Sno: 2,
          Level_unique: 2,
          Level_Table: "FEEDER_DATA",
          Level_TabName: null,
          Level_Primary_Key: "Feeder_id",
          Item_Name: "Department Feeder",
          Item_Count: 0,
          ItemKey: "Feeder_id",
          defaultNameField: "Feeder_Name",
          LevelContinue: true,
          Level_Index: 4,
          skipColumns: [],
          child_Sno: [1, 2],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 6,
      Level_Name: "Distribution Board / Capacitor",
      Level_Data: [
        {
          Flow_No: 1,
          Level_No: 6,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "DB_DATA",
          Level_TabName: null,
          Level_Primary_Key: "Board_Id",
          Item_Name: "Distribution Board",
          Item_Count: 0,
          ItemKey: "Board_Id",
          defaultNameField: "DB_Name",
          LevelContinue: false,
          Level_Index: 5,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 1,
          Level_No: 6,
          Level_Sno: 2,
          Level_unique: 2,
          Level_Table: "CAP_DATA",
          Level_TabName: null,
          Level_Primary_Key: "Cap_id",
          Item_Name: "Capacitor",
          Item_Count: 0,
          ItemKey: "Cap_id",
          defaultNameField: "Cap_Name",
          LevelContinue: false,
          Level_Index: 5,
          skipColumns: ["MV_Panel_Id"],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow1path {
  Data = [
    {
      name: "PowerTransformers",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}
export class Flow1tableData {
  Data = [
    {
      Flow_No: 1,
      Level_No: 1,
      Level_Name: "Power Transformer",
      Items: [
        {
          Serial_No: 1,
          Level_Sno: 1,
          Level_Primary_Key: "PT_Id",
          defaultNameField: "PT_Name",
          childElements: [2],
          parentElements: [],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 2,
      Level_Name: "Distribution Transformer",
      Items: [
        {
          Serial_No: 2,
          Level_Sno: 2,
          Level_Primary_Key: "DT_Id",
          defaultNameField: "DT_Name",
          childElements: [3],
          parentElements: [1],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 3,
      Level_Name: "Power House",
      Items: [
        {
          Serial_No: 3,
          Level_Sno: 3,
          Level_Primary_Key: "PH_Id",
          defaultNameField: "PH_Name",
          childElements: [4],
          parentElements: [2],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 4,
      Level_Name: "MV Panel",
      Items: [
        {
          Serial_No: 4,
          Level_Sno: 4,
          Level_Primary_Key: "MV_Panel_Id",
          defaultNameField: "MV_Panel_Name",
          childElements: [5, 6],
          parentElements: [3],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 5,
      Level_Name: "Capacitor / Department Feeder",
      Items: [
        {
          Serial_No: 5,
          Level_Sno: 1,
          Level_Primary_Key: "Cap_id",
          defaultNameField: "Cap_Name",
          childElements: [],
          parentElements: [4],
        },
        {
          Serial_No: 6,
          Level_Sno: 1,
          Level_Name: "Department Feeder",
          Level_Primary_Key: "Feeder_id",
          defaultNameField: "Feeder_Name",
          childElements: [7, 8],
          parentElements: [4],
        },
      ],
    },
    {
      Flow_No: 1,
      Level_No: 6,
      Serial_No: 7,
      Level_Name: "Distribution Board",
      Items: [
        {
          Serial_No: 7,
          Level_Sno: 1,
          Level_Primary_Key: "Board_Id",
          defaultNameField: "DB_Name",
          childElements: [],
          parentElements: [6],
        },
        {
          Serial_No: 8,
          Level_Sno: 2,
          Level_Name: "Capacitor",
          Level_Primary_Key: "Cap_id",
          defaultNameField: "Cap_Name",
          childElements: [],
          parentElements: [6],
        },
      ],
    },
  ];
}

// Flow-2
export class Flow2 {
  Data = [
    {
      Flow_No: 2,
      Level_No: 1,
      Level_Name: "Humidification System",
      Level_Data: [
        {
          Flow_No: 2,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "HMP_DATA",
          Level_TabName: "humidification_plant",
          Level_Primary_Key: "HMP_Id",
          Item_Name: "Humidification System",
          Item_Count: 0,
          ItemKey: "HMP_Id",
          defaultNameField: "HMP_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [1, 2, 3, 4, 5, 6, 7],
        },
      ],
    },
    {
      Flow_No: 2,
      Level_No: 2,
      Level_Name:
        "Motor / AWES / OHTC / Stabiliser / Chillar Plant / Supplier Air / Exhaust system",
      Level_Data: [
        {
          Flow_No: 2,
          Level_No: 2,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "MOTOR_DATA",
          Level_TabName: "motor_name_plate_details",
          Level_Primary_Key: "Motor_Id",
          Item_Name: "Motor",
          Item_Count: 0,
          ItemKey: "Motor_Id",
          defaultNameField: "Motor_Name",
          LevelContinue: true,
          Level_Index: 1,
          skipColumns: ["Mac_Id", "AWES_Id", "OHTC_Id"],
          child_Sno: [1, 2],
        },
        {
          Flow_No: 2,
          Level_No: 2,
          Level_Sno: 2,
          Level_unique: 2,
          Level_Table: "AWES_DATA",
          Level_TabName: "awes_details",
          Level_Primary_Key: "AWES_Id",
          Item_Name: "AWES",
          Item_Count: 0,
          ItemKey: "AWES_Id",
          defaultNameField: "AWES_Name",
          LevelContinue: true,
          Level_Index: 1,
          skipColumns: ["Mac_Id"],
          child_Sno: [3],
        },
        {
          Flow_No: 2,
          Level_No: 2,
          Level_Sno: 3,
          Level_unique: 3,
          Level_Table: "OHTC_DATA",
          Level_TabName: "ohtc_details",
          Level_Primary_Key: "OHTC_Id",
          Item_Name: "OHTC",
          Item_Count: 0,
          ItemKey: "OHTC_Id",
          defaultNameField: "OHTC_Name",
          LevelContinue: true,
          Level_Index: 1,
          skipColumns: ["Mac_Id"],
          child_Sno: [4],
        },
        {
          Flow_No: 2,
          Level_No: 2,
          Level_Sno: 4,
          Level_unique: 4,
          Level_Table: "STA_DATA",
          Level_TabName: "stabilizers",
          Level_Primary_Key: "Sta_Id",
          Item_Name: "Stabiliser",
          Item_Count: 0,
          ItemKey: "Sta_Id",
          defaultNameField: "Sta_Name",
          LevelContinue: false,
          Level_Index: 1,
          skipColumns: ["Mac_Id"],
          child_Sno: [],
        },
        {
          Flow_No: 2,
          Level_No: 2,
          Level_Sno: 5,
          Level_unique: 5,
          Level_Table: "CHILLER_DATA",
          Level_TabName: "chillar_plant",
          Level_Primary_Key: "Chi_Plant_Id",
          Item_Name: "Chillar Plant",
          Item_Count: 0,
          ItemKey: "Chi_Plant_Id",
          defaultNameField: "Chi_Name",
          LevelContinue: false,
          Level_Index: 1,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 2,
          Level_No: 2,
          Level_Sno: 6,
          Level_unique: 6,
          Level_Table: "SUP_AIR_DATA",
          Level_TabName: "supply_air_systems",
          Level_Primary_Key: "Supp_Air_Sys_Id",
          Item_Name: "Supplier Air",
          Item_Count: 0,
          ItemKey: "Supp_Air_Sys_Id",
          defaultNameField: "SAF_Name",
          LevelContinue: false,
          Level_Index: 1,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 2,
          Level_No: 2,
          Level_Sno: 7,
          Level_unique: 7,
          Level_Table: "EXHAUST_DATA",
          Level_TabName: "exhaust_system",
          Level_Primary_Key: "Exhaust_Id",
          Item_Name: "Exhaust system",
          Item_Count: 0,
          ItemKey: "Exhaust_Id",
          defaultNameField: "EXHAUST_Name",
          LevelContinue: false,
          Level_Index: 1,
          skipColumns: ["Exh_plant_id", "Mac_Id"],
          child_Sno: [],
        },
      ],
    },
    {
      Flow_No: 2,
      Level_No: 3,
      Level_Name: "Inverter / Capacitor / Motor",
      Level_Data: [
        {
          Flow_No: 2,
          Level_No: 3,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "INV_DATA",
          Level_TabName: "inverters",
          Level_Primary_Key: "Inv_Id",
          Item_Name: "Inverter",
          Item_Count: 0,
          ItemKey: "Inv_Id",
          defaultNameField: "Inv_Name",
          LevelContinue: false,
          Level_Index: 2,
          skipColumns: ["HMP_Id"],
          child_Sno: [],
        },
        {
          Flow_No: 2,
          Level_No: 3,
          Level_Sno: 2,
          Level_unique: 2,
          Level_Table: "CAP_DATA",
          Level_TabName: "capacitors",
          Level_Primary_Key: "Cap_id",
          Item_Name: "Capacitor",
          Item_Count: 0,
          ItemKey: "Cap_id",
          defaultNameField: "Cap_Name",
          LevelContinue: false,
          Level_Index: 2,
          skipColumns: ["MV_Panel_Id", "Feeder_id"],
          child_Sno: [],
        },
        {
          Flow_No: 2,
          Level_No: 3,
          Level_Sno: 3,
          Level_unique: 3,
          Level_Table: "MOTOR_DATA",
          Level_TabName: "motor_name_plate_details",
          Level_Primary_Key: "Motor_Id",
          Item_Name: "Motor",
          Item_Count: 0,
          ItemKey: "Motor_Id",
          defaultNameField: "Motor_Name",
          LevelContinue: true,
          Level_Index: 2,
          skipColumns: ["HMP_Id", "Mac_Id", "AWES_Id", "OHTC_Id"],
          child_Sno: [1, 2],
        },
        {
          Flow_No: 2,
          Level_No: 3,
          Level_Sno: 4,
          Level_unique: 4,
          Level_Table: "MOTOR_DATA",
          Level_TabName: "motor_name_plate_details",
          Level_Primary_Key: "Motor_Id",
          Item_Name: "Motor",
          Item_Count: 0,
          ItemKey: "Motor_Id",
          defaultNameField: "Motor_Name",
          LevelContinue: true,
          Level_Index: 2,
          skipColumns: ["HMP_Id", "Mac_Id", "AWES_Id", "OHTC_Id"],
          child_Sno: [1, 2],
        },
      ],
    },
    {
      Flow_No: 2,
      Level_No: 4,
      Level_Name: "Inverter / Capacitor",
      Level_Data: [
        {
          Flow_No: 2,
          Level_No: 4,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "INV_DATA",
          Level_TabName: "inverters",
          Level_Primary_Key: "Inv_Id",
          Item_Name: "Inverter",
          Item_Count: 0,
          ItemKey: "Inv_Id",
          defaultNameField: "Inv_Name",
          LevelContinue: false,
          Level_Index: 3,
          skipColumns: ["HMP_Id"],
          child_Sno: [],
        },
        {
          Flow_No: 2,
          Level_No: 4,
          Level_Sno: 2,
          Level_unique: 2,
          Level_Table: "CAP_DATA",
          Level_TabName: "capacitors",
          Level_Primary_Key: "Cap_id",
          Item_Name: "Capacitor",
          Item_Count: 0,
          ItemKey: "Cap_id",
          defaultNameField: "Cap_Name",
          LevelContinue: false,
          Level_Index: 3,
          skipColumns: ["MV_Panel_Id", "Feeder_id"],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow2path {
  Data = [
    {
      name: "Humidification System",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-3
export class Flow3 {
  Data = [
    {
      Flow_No: 3,
      Level_No: 1,
      Level_Name:
        "Blow Room / Cards / Drawing / Comber Preparatory / Combers / Fly Frames / Ring Spg / Cone Winders / Auto Coners / OE Spinning / Ring doubling / TFO",
      Level_Data: [
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Blow Room",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 2,
          Level_unique: 2,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Cards",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 3,
          Level_unique: 3,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Drawing",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 4,
          Level_unique: 4,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Comber Preparatory",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 5,
          Level_unique: 5,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Combers",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 6,
          Level_unique: 6,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Fly Frames",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 7,
          Level_unique: 7,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Ring Spg",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 8,
          Level_unique: 8,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Cone Winders",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 9,
          Level_unique: 9,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Auto Coners",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 10,
          Level_unique: 10,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "OE Spinning",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 11,
          Level_unique: 11,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Cheese winders",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 12,
          Level_unique: 12,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "Ring doubling",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 1,
          Level_Sno: 13,
          Level_unique: 13,
          Level_Table: "MAC_DATA",
          Level_TabName: "machinery_master",
          Level_Primary_Key: "Mac_Id",
          Item_Name: "TFO",
          Item_Count: 0,
          ItemKey: "Mac_Id",
          defaultNameField: "Mac_Name",
          LevelContinue: true,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
    {
      Flow_No: 3,
      Level_No: 2,
      Level_Name: "Motor / AWES / OHTC / Stabiliser / Exhaust system",
      Level_Data: [
        {
          Flow_No: 3,
          Level_No: 2,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "MOTOR_DATA",
          Level_TabName: "motor_name_plate_details",
          Level_Primary_Key: "Motor_Id",
          Item_Name: "Motor",
          Item_Count: 0,
          ItemKey: "Motor_Id",
          defaultNameField: "Motor_Name",
          LevelContinue: true,
          Level_Index: 1,
          skipColumns: ["HMP_Id", , "AWES_Id", "OHTC_Id"],
          child_Sno: [1, 2],
        },
        {
          Flow_No: 3,
          Level_No: 2,
          Level_Sno: 2,
          Level_unique: 2,
          Level_Table: "AWES_DATA",
          Level_TabName: "awes_details",
          Level_Primary_Key: "AWES_Id",
          Item_Name: "AWES",
          Item_Count: 0,
          ItemKey: "AWES_Id",
          defaultNameField: "AWES_Name",
          LevelContinue: true,
          Level_Index: 1,
          skipColumns: ["HMP_Id", "Process_id"],
          child_Sno: [3],
        },
        {
          Flow_No: 3,
          Level_No: 2,
          Level_Sno: 3,
          Level_unique: 3,
          Level_Table: "OHTC_DATA",
          Level_TabName: "ohtc_details",
          Level_Primary_Key: "OHTC_Id",
          Item_Name: "OHTC",
          Item_Count: 0,
          ItemKey: "OHTC_Id",
          defaultNameField: "OHTC_Name",
          LevelContinue: true,
          Level_Index: 1,
          skipColumns: ["HMP_Id", "AWES_Id"],
          child_Sno: [4],
        },
        {
          Flow_No: 3,
          Level_No: 2,
          Level_Sno: 4,
          Level_unique: 4,
          Level_Table: "STA_DATA",
          Level_TabName: "stabilizers",
          Level_Primary_Key: "Sta_Id",
          Item_Name: "Stabiliser",
          Item_Count: 0,
          ItemKey: "Sta_Id",
          defaultNameField: "Sta_Name",
          LevelContinue: false,
          Level_Index: 1,
          skipColumns: ["HMP_Id"],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 2,
          Level_Sno: 5,
          Level_unique: 5,
          Level_Table: "EXHAUST_DATA",
          Level_TabName: "exhaust_system",
          Level_Primary_Key: "Exhaust_Id",
          Item_Name: "Exhaust system",
          Item_Count: 0,
          ItemKey: "Exhaust_Id",
          defaultNameField: "EXHAUST_Name",
          LevelContinue: false,
          Level_Index: 1,
          skipColumns: ["HMP_Id"],
          child_Sno: [],
        },
      ],
    },
    {
      Flow_No: 3,
      Level_No: 3,
      Level_Name: "Inverter / Capacitor / Motor",
      Level_Data: [
        {
          Flow_No: 3,
          Level_No: 3,
          Level_Sno: 3,
          Level_unique: 1,
          Level_Table: "INV_DATA",
          Level_TabName: "inverters",
          Level_Primary_Key: "Inv_Id",
          Item_Name: "Inverter",
          Item_Count: 0,
          ItemKey: "Inv_Id",
          defaultNameField: "Inv_Name",
          LevelContinue: false,
          Level_Index: 2,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 3,
          Level_Sno: 4,
          Level_unique: 2,
          Level_Table: "CAP_DATA",
          Level_TabName: "capacitors",
          Level_Primary_Key: "Cap_id",
          Item_Name: "Capacitor",
          Item_Count: 0,
          ItemKey: "Cap_id",
          defaultNameField: "Cap_Name",
          LevelContinue: false,
          Level_Index: 2,
          skipColumns: ["MV_Panel_Id", "Feeder_id"],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 3,
          Level_Sno: 1,
          Level_unique: 3,
          Level_Table: "MOTOR_DATA",
          Level_TabName: "motor_name_plate_details",
          Level_Primary_Key: "Motor_Id",
          Item_Name: "Motor",
          Item_Count: 0,
          ItemKey: "Motor_Id",
          defaultNameField: "Motor_Name",
          LevelContinue: true,
          Level_Index: 2,
          skipColumns: ["HMP_Id", "Mac_Id", "OHTC_Id"],
          child_Sno: [1, 2],
        },
        {
          Flow_No: 3,
          Level_No: 3,
          Level_Sno: 2,
          Level_unique: 4,
          Level_Table: "MOTOR_DATA",
          Level_TabName: "motor_name_plate_details",
          Level_Primary_Key: "Motor_Id",
          Item_Name: "Motor",
          Item_Count: 0,
          ItemKey: "Motor_Id",
          defaultNameField: "Motor_Name",
          LevelContinue: true,
          Level_Index: 2,
          skipColumns: ["HMP_Id", "Mac_Id", "OHTC_Id"],
          child_Sno: [1, 2],
        },
      ],
    },
    {
      Flow_No: 3,
      Level_No: 4,
      Level_Name: "Inverter / Capacitor",
      Level_Data: [
        {
          Flow_No: 3,
          Level_No: 4,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "INV_DATA",
          Level_TabName: "inverters",
          Level_Primary_Key: "Inv_Id",
          Item_Name: "Inverter",
          Item_Count: 0,
          ItemKey: "Inv_Id",
          defaultNameField: "Inv_Name",
          LevelContinue: false,
          Level_Index: 3,
          skipColumns: [],
          child_Sno: [],
        },
        {
          Flow_No: 3,
          Level_No: 4,
          Level_Sno: 2,
          Level_unique: 2,
          Level_Table: "CAP_DATA",
          Level_TabName: "capacitors",
          Level_Primary_Key: "Cap_id",
          Item_Name: "Capacitor",
          Item_Count: 0,
          ItemKey: "Cap_id",
          defaultNameField: "Cap_Name",
          LevelContinue: false,
          Level_Index: 3,
          skipColumns: ["MV_Panel_Id", "Feeder_id"],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow3path {
  Data = [
    {
      name: "Blow Room",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-4
export class Flow4 {
  Data = [
    {
      Flow_No: 4,
      Level_No: 1,
      Level_Name: "Compressor",
      Level_Data: [
        {
          Flow_No: 4,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "COMP_DATA",
          Level_TabName: "compressor_details",
          Level_Primary_Key: "Comp_Id",
          Item_Name: "Compressor",
          Item_Count: 0,
          ItemKey: "Comp_Id",
          defaultNameField: "Comp_Name",
          LevelContinue: false,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow4path {
  Data = [
    {
      name: "Compressor",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-5
export class Flow5 {
  Data = [
    {
      Flow_No: 5,
      Level_No: 1,
      Level_Name: "Lighting",
      Level_Data: [
        {
          Flow_No: 5,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "LIGHT_DATA",
          Level_TabName: "lighting_details_depts",
          Level_Primary_Key: "Lighting_Id",
          Item_Name: "Lighting",
          Item_Count: 0,
          ItemKey: "Lighting_Id",
          defaultNameField: "Lighting_Name",
          LevelContinue: false,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow5path {
  Data = [
    {
      name: "Lighting",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-6
export class Flow6 {
  Data = [
    {
      Flow_No: 6,
      Level_No: 1,
      Level_Name: "Boiler",
      Level_Data: [
        {
          Flow_No: 6,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "BOILER_DATA",
          Level_TabName: "boiler_details",
          Level_Primary_Key: "Boiler_id",
          Item_Name: "Boiler",
          Item_Count: 0,
          ItemKey: "Boiler_id",
          defaultNameField: "Boiler_Name",
          LevelContinue: false,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow6path {
  Data = [
    {
      name: "Boiler",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-7
export class Flow7 {
  Data = [
    {
      Flow_No: 7,
      Level_No: 1,
      Level_Name: "Thermopac",
      Level_Data: [
        {
          Flow_No: 7,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "THERMOPAC_DATA",
          Level_TabName: "thermopac_details",
          Level_Primary_Key: "Thermopac_id",
          Item_Name: "Thermopac",
          Item_Count: 0,
          ItemKey: "Thermopac_id",
          defaultNameField: "Thermopac_Name",
          LevelContinue: false,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow7path {
  Data = [
    {
      name: "Thermopac",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-8
export class Flow8 {
  Data = [
    {
      Flow_No: 8,
      Level_No: 1,
      Level_Name: "Generator",
      Level_Data: [
        {
          Flow_No: 8,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "GEN_DATA",
          Level_TabName: "generator",
          Level_Primary_Key: "Gen_Id",
          Item_Name: "Generator",
          Item_Count: 0,
          ItemKey: "Gen_Id",
          defaultNameField: "Gen_Name",
          LevelContinue: false,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow8path {
  Data = [
    {
      name: "Generator",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-9
export class Flow9 {
  Data = [
    {
      Flow_No: 9,
      Level_No: 1,
      Level_Name: "Solar Power Plant",
      Level_Data: [
        {
          Flow_No: 9,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "SOLAR_DATA",
          Level_TabName: "solar_power_plant",
          Level_Primary_Key: "Solar_Id",
          Item_Name: "Solar Power Plant",
          Item_Count: 0,
          ItemKey: "Solar_Id",
          defaultNameField: "Solar_Name",
          LevelContinue: false,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow9path {
  Data = [
    {
      name: "Solar Power Plant",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-10
export class Flow10 {
  Data = [
    {
      Flow_No: 10,
      Level_No: 1,
      Level_Name: "Dryer",
      Level_Data: [
        {
          Flow_No: 10,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "DRYER_DATA",
          Level_TabName: "dryer_details",
          Level_Primary_Key: "Dryer_id",
          Item_Name: "Dryer",
          Item_Count: 0,
          ItemKey: "Dryer_id",
          defaultNameField: "Dryer_Name",
          LevelContinue: false,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow10path {
  Data = [
    {
      name: "Dryer",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}

// Flow-11
export class Flow11 {
  Data = [
    {
      Flow_No: 11,
      Level_No: 1,
      Level_Name: "YCP",
      Level_Data: [
        {
          Flow_No: 11,
          Level_No: 1,
          Level_Sno: 1,
          Level_unique: 1,
          Level_Table: "YCP_DATA",
          Level_TabName: "ycp_details",
          Level_Primary_Key: "YCP_Id",
          Item_Name: "YCP",
          Item_Count: 0,
          ItemKey: "YCP_Id",
          defaultNameField: "YCP_name",
          LevelContinue: false,
          Level_Index: 0,
          skipColumns: [],
          child_Sno: [],
        },
      ],
    },
  ];
}
export class Flow11path {
  Data = [
    {
      name: "YCP",
      activeIndex: 0,
      activeParentId: "",
      activeParentKey: "",
      activeChildSno: [],
    },
  ];
}
